### ISSUE TITLE
OpenChannel Error

### ISSUE THREAD

**Issue by EmiliaVieira** [pootmhicnought/Delphi_AMQP#6] opened 2024-01-16 15:06 UTC
I need to open two channels, on the same connection, each one will be responsible for a task.
In the source code it would look like this:
procedure TTestbenchForm.ButtonOpenChannelClick(Sender: TObject);
begin
  **Channel1 := AMQP.OpenChannel;
  Channel2 := AMQP.OpenChannel;**
end;
But in the second OpenChannel the error occurs: access violation at 0x00890a34 reading from address 0x00000000.
because in the second TAMQPConnection.OpenChannel in the line **Frame := Result.Queue.Get(FTimeout);**
the Frame becomes **nil**.
According to what I researched, in an application with multiple tasks it is recommended to open a channel for each task,
all channels within the same connection.
I didn't quite understand how in the first OpenChannel, Result.Queue.Get manages to find a message.
Is it possible to make the second one also find it, so that more than one channel can be opened in sequence?

**Comment by ghost** [comment] 2024-01-17 01:24
I think this might be a bug Delphi in TQueueHelper or TListHelper

Haven't tracked it down fully yet, but I see evidence that something isn't working properly in there.

What version of Delphi are you using?


     On Tuesday, January 16, 2024 at 07:06:47 AM PST, EmiliaVieira ***@***.***> wrote:  
 
 


I need to open two channels, on the same connection, each one will be responsible for a task.
In the source code it would look like this:
procedure TTestbenchForm.ButtonOpenChannelClick(Sender: TObject);
begin
Channel1 := AMQP.OpenChannel;
Channel2 := AMQP.OpenChannel;
end;
But in the second OpenChannel the error occurs: access violation at 0x00890a34 reading from address 0x00000000.
because in the second TAMQPConnection.OpenChannel in the line Frame := Result.Queue.Get(FTimeout);
the Frame becomes nil.
According to what I researched, in an application with multiple tasks it is recommended to open a channel for each task,
all channels within the same connection.
I didn't quite understand how in the first OpenChannel, Result.Queue.Get manages to find a message.
Is it possible to make the second one also find it, so that more than one channel can be opened in sequence?

**Comment by EmiliaVieira** [comment] 2024-01-17 10:54
Thanks for answering, I'm using **Delphi 10.3**
It is possible to simulate the error using the TestbenchWin example that you provided.
In my application, I will have several threads, each with its own channel and I need to start them all at program startup, in the second OpenChannel occurs the error.

**Comment by ghost** [comment] 2024-01-17 12:59
I had no problem duplicating by adding and opening another channel component.

The issue appears to be inconsistent behavior of the RTL helper classes. The solution that comes to my mind is refactoring the communication queue handler as from my standpoint it's far too complex anyway. 

You might want to look back to the original source of AMQP,https://github.com/delphiripper/comotobo

There are tons of forks and it's possible that one of those forks has already fixed the problem. I'm not sure when I'll have time to make a fix.


     On Wednesday, January 17, 2024 at 02:54:21 AM PST, EmiliaVieira ***@***.***> wrote:  
 
 


Thanks for answering, I'm using Delphi 10.3
It is possible to simulate the error using the TestbenchWin example that you provided.
In my application, I will have several threads, each with its own channel and I need to start them all at program startup, in the second OpenChannel occurs the error.

**Comment by EmiliaVieira** [comment] 2024-01-17 20:11
Thanks for answering, no one has fixed this bug yet.
It occurs whenever more than one IAMQPChannel is declared and the OpenChannel of the second is called while the first channel is still open.
The problem appears to be in the **FQueue.Dequeue** of the TBlockingQueue<T>.Get(ATimeOut: LongWord): T;
from the AMQP.Classes unit, even FQueue.Count = 1, FQueue.Dequeue returns **nil**. I thought it was due to some competition and another thread might be accessing the same FQueue, but the block is inside a CriticalSection.
I will continue trying to find a solution.
![Channel2-A](https://github.com/pootmhicnought/Delphi_AMQP/assets/39424499/cf7de7c3-033d-4c03-9280-8ddda6320877)
![Channel2-B](https://github.com/pootmhicnought/Delphi_AMQP/assets/39424499/ee472adb-b6f4-4095-9f9e-975f6a982bdf)

**Comment by ghost** [comment] 2024-01-17 21:32
I followed it all the way down into TQueueHelper in the System.Generics.Collection unit. I traced through the TQueueHelper adding things to the queue and then when the second channel tried to dequeue the TQueueHelper head/tail pointers indicated there was 1 entry in the list however the TQueueHelper.FLH TListHelper was empty.

Root cause may be in TListHelper, but I wasn't able to pinpoint where it goes off the rails.

Both of these helper record types look overly complicated, and being it's in the RTL fixing become problematic. 

It could be bad usage higher up, however it sure looked like this outta work ;-)

     On Wednesday, January 17, 2024 at 12:11:15 PM PST, EmiliaVieira ***@***.***> wrote:  
 
 


Thanks for answering, no one has fixed this bug yet.
It occurs whenever more than one IAMQPChannel is declared and the OpenChannel of the second is called while the first channel is still open.
The problem appears to be in the FQueue.Dequeue of the TBlockingQueue.Get(ATimeOut: LongWord): T;
from the AMQP.Classes unit, even FQueue.Count = 1, FQueue.Dequeue returns nil. I thought it was due to some competition and another thread might be accessing the same FQueue, but the block is inside a CriticalSection.
I will continue trying to find a solution.
Channel2-A.png (view on web)
Channel2-B.png (view on web)

**Comment by ghost** [comment] 2024-01-18 00:03
Might have found the problem. At least for my test. 

 AMQP.MaxChannel := 2;

AMQP was closing the channel after it connected because default MaxChannel = 1. 

In my test I simply added another AMQPChannel to the test bench when handling the OpenChannel button.


     On Wednesday, January 17, 2024 at 12:11:15 PM PST, EmiliaVieira ***@***.***> wrote:  
 
 


Thanks for answering, no one has fixed this bug yet.
It occurs whenever more than one IAMQPChannel is declared and the OpenChannel of the second is called while the first channel is still open.
The problem appears to be in the FQueue.Dequeue of the TBlockingQueue.Get(ATimeOut: LongWord): T;
from the AMQP.Classes unit, even FQueue.Count = 1, FQueue.Dequeue returns nil. I thought it was due to some competition and another thread might be accessing the same FQueue, but the block is inside a CriticalSection.
I will continue trying to find a solution.
Channel2-A.png (view on web)
Channel2-B.png (view on web)

**Comment by EmiliaVieira** [comment] 2024-01-18 00:37
That's right! I increased MaxChannel and it worked for me too. **Thanks a lot!!!**
I'm so happy, I was already losing sleep over it. Thanks! ;-)

**Comment by ghost** [comment] 2024-01-18 03:05
Glad I was able to track it down and it was simple! 


     On Wednesday, January 17, 2024 at 04:38:00 PM PST, EmiliaVieira ***@***.***> wrote:  
 
 


That's right! I increased MaxChannel and it worked for me too. Thanks a lot!!!
I'm so happy, I was already losing sleep over it. Thanks! ;-)

**Closed as completed** 2024-01-18 10:44 UTC
